# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzcxOWE5YzRkMzJhZmZjOTEwOTMzZjBhMGY5YzMxMmMzNGRiODQyNzdjMWY1OTAxM2RjYTczMzgyYjBlN2U3MTE5NTkyMjVhOGU5MWFkMzY5NjE0MGQyYTM2YzQwYjI0N2NhOGQ1ZGM5ZmUyNTdkOTg0MzAzYTRlMGE2NzQ4MzU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
